### ISSUE TITLE
Splash-jupyter crashed by latest ipykernel

### ISSUE THREAD

**Issue by genius001** [scrapinghub/splash#396]
After deep research, I found the reason by the latest version ipykernel.(update 02/26/2016)
Seems the file [kernelbase.py ](https://github.com/ipython/ipykernel/blob/master/ipykernel/kernelbase.py)has changed. so the error occurred.

the log:
> 
[I 01:53:05.136 NotebookApp] Kernel started: 52daf4a0-7d8a-4c56-8a08-8eb26c2849ce
Xlib:  extension "RANDR" missing on display ":1".
[IPKernelApp] ERROR | UNKNOWN MESSAGE TYPE: 'comm_open'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/xiaoming/.pyenv/versions/py3-splash/lib/python3.4/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/xiaoming/.pyenv/versions/py3-splash/lib/python3.4/site-packages/splash/kernel/kernelbase.py", line 76, in execute_request
    md = self._make_metadata(parent['metadata'])
AttributeError: 'SplashKernel' object has no attribute '_make_metadata'

BTW, The problem happened while I'm installing the splash-jupyter,
Last second the ipykernel was 4.x.x, the next second the ipykernel has update to 4.3.1.
Aha.

**Comment by kmike** [comment]
Thanks @genius001, it looks like our hacky kernel implementation was broken by https://github.com/ipython/ipykernel/pull/71.
